[phases.setup]
nixPkgs = [
  "glibc",
  "glibcLocales",
  "gcc",
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "opencv",
  "mesa",
  "mesa_glu",
  "freeglut",
  "libGL",  # Corrected from 'libgl' to 'libGL'
  "libGLU",
  "xorg.libX11"  # Corrected lowercase name
]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "python extract.py"
