[phases.setup]
nixPkgs = [
  "glibc",
  "glibcLocales",
  "gcc",
  "python312",
  "opencv",
  "mesa",
  "mesa_glu",
  "freeglut",
  "libGL",
  "libGLU",
  "libX11"  # Corrected package name
]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "python extract.py"
