[phases.setup]
nixPkgs = ["glibc", "glibcLocales", "gcc"]
cmds = [
  "apt-get update && apt-get install -y libgl1-mesa-glx" # Install OpenCV dependency
]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "python extract.py"
