[phases.setup]
cmds = [
  "apt-get update && apt-get install -y libgl1-mesa-glx" # Install OpenCV dependency
]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "python app.py"
