[phases.setup]
nixPkgs = [
  "glibc",
  "glibcLocales",
  "gcc",
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "opencv",
  "mesa",
  "mesa_glu",
  "freeglut",
  "libgl",
  "libglu",
  "libx11"  # Corrected lowercase name
]

[phases.build]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && python extract.py"
